### ISSUE TITLE
Cargo audit reports several vulnerable dependencies

### ISSUE THREAD

**Issue by ChrisGreenaway** [tomtau/tmkms-light#36]
**Describe the bug**
Running cargo audit found four vulnerable dependencies:
1.	RUSTSEC-2021-0119 in nix 0.20.0 – requires upgrade to >=0.23.0
2.	RUSTSEC-2022-0013 in regex 1.5.4 – requires upgrade to >=1.5.5
3.	RUSTSEC-2020-0071 in time 0.1.43 – requires update to >=0.2.23
4.	RUSTSEC-2021-0124 in tokio 0.2.25 – requires upgrade to >=1.13.1

**To Reproduce**
1. Run cargo audit

**Expected behavior**
No vulnerable dependencies shown.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by tomtau** [comment]
moved to https://github.com/crypto-com/tmkms-light/issues/341
