### ISSUE TITLE
Cargo audit reports several unmaintained dependencies

### ISSUE THREAD

**Issue by ChrisGreenaway** [tomtau/tmkms-light#37]
**Describe the bug**
Running cargo audit found three unmaintained dependencies: failure, net2 and serde_cbor.

**To Reproduce**
1. Run cargo audit

**Expected behavior**
No unmaintained dependencies shown.

**Desktop:**
 - OS: Ubuntu
 - Version 22.04

**Comment by tomtau** [comment]
moved to https://github.com/crypto-com/tmkms-light/issues/341
