### ISSUE TITLE
Inconsistent exit code with errors loading enclave config during launch-all

### ISSUE THREAD

**Issue by ChrisGreenaway** [tomtau/tmkms-light#38]
**Describe the bug**
By inspection, the following code in `EnclaveConfig::from_file` can panic:
```
let toml_string = fs::read_to_string(config_path).expect("toml config file read");
```

This would lead to an exit code of `101` being returned rather than an exit code of `1`.

This could panic if:
 * The file is deleted after the existence check that happens before this line
 * The file does not contain valid UTF-8
 * There is some permission problem reading the file

It's a shame because the `EnclaveConfig::from_file` function returns a `Result`, so the `Result` from `read_to_string` should be easy to handle.

**To Reproduce**
1. Create an enclave config file that is not readable by the current user
2. Run tmkms-nitro-helper launch-all

**Expected behavior**
Expected exit code of 1 to indicate an error state. Actual behaviour - exit code 101 (panic).

**Desktop:**
 - OS: Ubuntu
 - Version 22.04

**Comment by tomtau** [comment]
moved to https://github.com/crypto-com/tmkms-light/issues/340
