### ISSUE TITLE
Cannot use standard vsock-proxy service with tmkms-nitro-helper

### ISSUE THREAD

**Issue by ant1g** [tomtau/tmkms-light#63]
**Describe the bug**

When installing the nitro-cli tooling on a nitro-enabled VM, a systemd service to manage the vsock-proxy is installed by default.
The service name is `nitro-enclaves-vsock-proxy.service` and it does exactly what you are doing with `tmkms-nitro-helper enclave vsock-proxy`.

If I use `nitro-enclaves-vsock-proxy.service` to manage the vsock-proxy, then the `tmkms-nitro-helper start` will fail with:
```
Oct 14 17:07:26 ip-10-56-1-65 tmkms: vsock proxy not started
```

**To Reproduce**
1. start `nitro-enclaves-vsock-proxy.service`
2. run `tmkms-nitro-helper start`

**Expected behavior**

I should be able to manage the vsock-proxy using the standard way and still be able to use tmkms.

I see that you are checking if proxy is running by looking at the running processes (`check_vsock_proxy()` function in nitro provider code).
Here is a `ps` output of the vsock-proxy standard service while running:
```
[ec2-user@ip-x-x-x-x ~]$ ps ax | grep vsock-proxy
21356 ?        Ssl    0:00 /usr/bin/vsock-proxy 8000 kms.x-x-x.amazonaws.com 443 --config /etc/nitro_enclaves/vsock-proxy.yaml
```

**Comment by tomtau** [comment]
https://github.com/crypto-com/tmkms-light/issues/442
